export const CHECK_NODE_STATUS_START = 'CHECK_NODE_STATUS_START';
export const CHECK_NODE_STATUS_SUCCESS = 'CHECK_NODE_STATUS_SUCCESS';
export const CHECK_NODE_STATUS_FAILURE = 'CHECK_NODE_STATUS_FAILURE';
export  const SET_LOADING_NODE_BLOCKS = 'SET_LOADING_NODE_BOCKS';
export  const SET_ERROR_NODE_BLOCKS = 'SET_ERROR_NODE_BLOCKS';
export  const SET_NODE_BLOCKS = 'SET_NODE_BLOCKS';
